import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";

export default function Player() {
  const router = useRouter();
  const { id } = router.query;
  const [data, setData] = useState(null);
  useEffect(() => {
    (async () => {
      if (id) {
        const response = await fetch(`/api/player/${id}`);
        const data = await response.json();
        setData(data);
      }
    })();
  }, [id]);
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>{data ? (data as any).username.replace(/_/g, " ") : ""}</h1>
        </div>
        <div>FFA Points: {data ? (data as any).ffaSkillPoints : ""}</div>
        <div>FFA Position: {data ? (data as any).ffaPosition : ""}</div>
        <div>1v1 Points: {data ? (data as any).OnevOneSkillPoints : ""}</div>
        <div>1v1 Position: {data ? (data as any).OnevOnePosition : ""}</div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
